version: "3.9"

services:
  app:
    build: ./
    command: ./main
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_DB: "d_content_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init/pg/:/docker-entrypoint-initdb.d/
      - dcdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure

volumes:
  dcdb-data: