version: "3.9"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "d_content_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init/pg/:/docker-entrypoint-initdb.d/
      - dcdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  dcdb-data: