version: "3.9"

services:
#  app:
#    build: ./
#    command: ./main
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: on-failure

  postgres:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${PG_DBNAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./init/pg/:/docker-entrypoint-initdb.d/
      - dcdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: on-failure

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - rds-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=1

volumes:
  dcdb-data:
  rds-data: