version: "3.9"

services:
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - TZ=${PG_TIMEZONE}
      - POSTGRES_DB=${PG_DBNAME}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./init/test/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    restart: on-failure

  redis:
    image: redis:latest
    expose:
      - "6379"
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=1